{% set name = "python-gmatelastoplasticqpot3d" %}
{% set version = "0.11.1" %}
{% set sha256 = "948988434d43735d65a478f82c524e01301eb2aa63eb5faa0564a658d3780035" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatElastoPlasticQPot3d/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - pyxtensor
    - gmattensor
    - gmatelastic
    - qpot
  run:
    - python

test:
  imports:
    - GMatElastoPlasticQPot3d

about:
  home: https://github.com/tdegeus/GMatElastoPlasticQPot3d
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Elasto-plastic model based on a manifold of quadratic potentials (Python wrapper).
  description: Elasto-plastic model based on a manifold of quadratic potentials (Python wrapper).
  doc_url: https://github.com/tdegeus/GMatElastoPlasticQPot3d
  dev_url: https://github.com/tdegeus/GMatElastoPlasticQPot3d

extra:
  recipe-maintainers:
    - tdegeus
